#!/usr/bin/env bash
# Prints the figures behind the page's "Measured in …" line (`measured` in
# src/data/suite.ts). Run from anywhere; the suite's repos are expected beside
# this one, as in ~/GitHub/magnetar-os/.
#
# Everything is read from each repo's committed `main` branch with git grep,
# so uncommitted work and build output (target/) never count:
#   - lines of Rust: every line of every tracked *.rs file;
#   - tests: lines that are a #[test] or #[tokio::test] attribute, optionally
#     with arguments. Doc tests and tests generated by macros are not counted;
#   - todo!() calls: lines containing `todo!(`.
#
# Usage: scripts/measure-suite.sh [ref]   (default ref: main)
set -euo pipefail

ref=${1:-main}
root=$(cd "$(dirname "$0")/../.." && pwd)
repos=(circle cosmic-ext-nib cosmic-ext-widgets cosmic-pim envelope grabit jump locket peek pencil pocket slate)
test_attr='^\s*#\[(tokio::)?test(\(.*\))?\]'

# git grep exits 1 when nothing matches; that is a count of zero, not an error.
grep_rs() { git -C "$dir" grep "$@" "$ref" -- '*.rs' || [ $? -eq 1 ]; }

total_lines=0 total_tests=0 total_todo=0
printf '%-20s %8s %6s %5s\n' repo lines tests todo
for repo in "${repos[@]}"; do
  dir=$root/$repo
  git -C "$dir" rev-parse --verify -q "$ref^{commit}" >/dev/null || { echo "$repo: no ref $ref" >&2; exit 1; }
  lines=$(grep_rs -hc '' | awk '{ s += $1 } END { print s + 0 }')
  tests=$(grep_rs -hE "$test_attr" | wc -l)
  todo=$(grep_rs -hF 'todo!(' | wc -l)
  printf '%-20s %8d %6d %5d\n' "$repo" "$lines" "$tests" "$todo"
  total_lines=$((total_lines + lines)) total_tests=$((total_tests + tests)) total_todo=$((total_todo + todo))
done
printf '%-20s %8d %6d %5d\n' total "$total_lines" "$total_tests" "$total_todo"
